name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18" # Set Node.js to v18 or higher

      - name: Install dependencies
        run: npm install

      - name: Install Angular CLI
        run: npm install -g @angular/cli # Install Angular CLI globally

      - name: Run predeploy script
        run: npm run predeploy # Run the predeploy script defined in your package.json

      - name: Check if dist folder exists
        run: |
          if [ ! -d "dist/angular-charts/browser" ]; then
            echo "Error: Build output not found. Please check your build configuration."
            exit 1
          fi

      - name: Set Git user identity
        run: |
          git config --global user.name "osamaalmidani"  # Replace with your name
          git config --global user.email "osama.al-midani@outlook.com"  # Replace with your email

      - name: Clean untracked files
        run: git clean -fdx # Remove untracked files and directories

      - name: Reset git to prevent issues
        run: |
          git reset --hard
          git clean -fd

      - name: Deploy to gh-pages
        run: |
          # Ensure the dist directory exists
          if [ ! -d "dist/angular-charts/browser" ]; then
            echo "Error: Build output not found. Please check your build configuration."
            exit 1
          fi

          # Deploy the build files to the gh-pages branch
          npx gh-pages -d dist/angular-charts/browser  # Use the deploy script to push the build to gh-pages

      - name: Set GitHub Pages Source to Versioned Branch
        run: |
          # Use GitHub API to update the Pages source to the new branch
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"source": {"branch": "gh-pages", "path": "/"}}' \
            https://api.github.com/repos/${{ github.repository }}/pages
