name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: write # Required for deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Run predeploy script
        run: npm run predeploy

      - name: Set Git user identity
        run: |
          git config --global user.name "osamaalmidani"
          git config --global user.email "osama.al-midani@outlook.com"

      - name: Delete old gh-pages branch
        run: |
          git push origin --delete gh-pages || echo "Branch not found, skipping deletion"

      - name: Generate new branch name
        run: echo "BRANCH_NAME=gh-pages-$(date +%Y%m%d-%H%M%S)" >> $GITHUB_ENV

      - name: Deploy to a new branch
        run: |
          if [ ! -d "dist/angular-charts/browser" ]; then
            echo "Error: Build output not found. Please check your build configuration."
            exit 1
          fi

          git checkout --orphan $BRANCH_NAME
          git rm -rf .
          cp -r dist/angular-charts/browser/* .
          touch .nojekyll  # Prevent Jekyll processing
          git add .
          git commit -m "Deployment: $BRANCH_NAME"
          git push origin $BRANCH_NAME --force

      - name: Update GitHub Pages to use the new branch
        run: |
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d "{\"source\": {\"branch\": \"$BRANCH_NAME\", \"path\": \"/\"}}" \
            https://api.github.com/repos/${{ github.repository }}/pages
