name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js with the version you need
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18" # Set Node.js to v18 or higher

      # Install dependencies (npm install)
      - name: Install dependencies
        run: npm install

      # Install Angular CLI globally
      - name: Install Angular CLI
        run: npm install -g @angular/cli

      # Run predeploy script to build the Angular app for production
      - name: Run predeploy script
        run: npm run predeploy # Run the predeploy script defined in your package.json

      # List the contents of dist/ to verify the build output
      - name: List contents of dist directory
        run: ls -alh dist/

      # Set Git user identity for pushing changes
      - name: Set Git user identity
        run: |
          git config --global user.name "osamaalmidani"  # Replace with your name
          git config --global user.email "osama.al-midani@outlook.com"  # Replace with your email

      # Deploy the built files to the gh-pages branch
      - name: Deploy to gh-pages
        run: |
          # Ensure the dist/angular-charts/browser directory exists
          if [ ! -d "dist/angular-charts/browser" ]; then
            echo "Error: Build output not found. Please check your build configuration."
            exit 1
          fi

          # Deploy the build files to the gh-pages branch using the GitHub Token for authentication
          npx gh-pages -d dist/angular-charts/browser -r https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
